package version

import (
	"fmt"
	"io"
	"strings"

	"cloudcc-customization-expert-go/internal/edition"
)

const Version = "2.2.37"
const CompatVersion = "2.5.3"

func Current() string {
	return Version + edition.VersionSuffix
}

func IsVersionAction(action string) bool {
	switch action {
	case "version", "-version", "--version", "-v", "--v", "help", "-help", "--help", "-h", "--h", "changelog", "doctor", "docs", "stats":
		return true
	default:
		return false
	}
}

func Handle(action string, args []string, stdout io.Writer, stderr io.Writer) error {
	switch normalize(action) {
	case "get":
		fmt.Fprintf(stdout, "\ncloudcc-cli-go version: %s\npackage: %s\ncompat cloudcc-cli version: %s\n\n", Current(), edition.PackageName, CompatVersion)
	case "help":
		Help(stdout, stderr)
		return nil
	case "changelog":
		fmt.Fprintln(stderr)
		fmt.Fprintln(stderr, "CloudCC Go skill CLI")
		fmt.Fprintln(stderr, "- CLI compatibility doctor now validates low-code CLI/MetadataService version gates and reports high-code CLI/setup-svc advisory baselines: 2.2.7 high-code publish recommends setup-svc 19.3.R20+, while 2.2.33 API registrar low-code metadata requires MetadataService 1.1.41+ and runtime/high-code remote invocation recommends setup-svc 19.7.R8+; setup-svc DEV/B/G/customer branches do not block by version string alone.")
		fmt.Fprintln(stderr, "- Retracted migration-specific classify, physical-preflight, evidence-archive, and direct catalog-output surfaces; existing object/field scan and create fixes remain available through the normal MSAPI contract.")
		fmt.Fprintln(stderr, "- Object/field database-fidelity closure preserves explicit nested display-thousands values before defaults, preserves object null/explicit remarks, and validates setup-svc physical slot families without comparing mutable SQL column types.")
		fmt.Fprintln(stderr, "- Menu/application guidance now clarifies that all IDs must come from CLI/service readback, object references should prefer object API name while still allowing real object ID/prefix, and omitted profile collections default to all runtime profiles.")
		fmt.Fprintln(stderr, "- Low-code module availability closure: object create now places in-plan business fields on generated default PC/mobile layouts, enriches default views and search layouts, expands embedded record types through profile/layout/default bindings, rejects missing application tab references, and returns profile/application readback evidence for acceptance gates.")
		fmt.Fprintln(stderr, "- Object-scoped MetadataService batch create now supports record types, page layouts, validation rules, and custom buttons with root-object enforcement, createOnly/skipExisting handling, item-level precheck results, and CLI user docs.")
		fmt.Fprintln(stderr, "- Project outputs governance now provides a non-overwriting root outputs scaffold and read-only doctor for dynamic documents, project-specific tools, data/deployment/training/integration packages, relative references, delivered-artifact SHA-256, and sensitive-content risk without imposing fixed content templates.")
		fmt.Fprintln(stderr, "- Advisory end-to-end test governance now provides a non-overwriting project scaffold, read-only impact recommendations, immutable human scope decisions, run manifests, and cloudcc doctor test-governance; recommendations remain non-blocking and do not replace target-role UAT or Go/No-Go.")
		fmt.Fprintln(stderr, "- Rollup summary field creation now requires MetadataService 1.1.36 for platform-compatible filtered summary readback: filtered summaries write tp_sys_condition MAIN_OBJ_ID/BOOL_FILTER rows and derive AGGCONDITIONDIS so filtered summary fields can be shown and edited correctly.")
		fmt.Fprintln(stderr, "- Project-standard governance now separates AGENTS read gates, long-lived standards, FEAT/ADR/DevOps facts, blueprint process artifacts, and dynamic task state; cloudcc doctor project-governance validates the local structure without writes, and release purity gates reject customer identifiers and local absolute paths.")
		fmt.Fprintln(stderr, "- Requirement-design and high-code platform-capability routing now requires business, functional, design, and high-code requests to prefer platform standard metadata before Java code when low-code capabilities can satisfy the requirement; even if the user classifies the request as high-code, the skill should name the low-code capability that can implement it before reserving code for unsupported external, cross-object, dynamic, governance, or complex orchestration cases.")
		fmt.Fprintln(stderr, "- High-code performance guidance now forbids generated classes, triggers, and timer helpers from calling cquery*/cqlQuery*/pagedQuery inside loops for per-row enrichment, duplicate checks, or existence checks; generated code should collect keys, query with IN or bounded batches, build lookup maps, and then assemble results.")
		fmt.Fprintln(stderr, "- High-code JSON return guidance now discourages net.sf.json JSONObject/JSONArray for generated business return structures because of performance and JSONNull risks; generated classes, triggers, and timer helpers should return Map<String,Object>, List<Map<String,Object>>, or explicit DTOs unless an existing fixed contract requires compatibility.")
		fmt.Fprintln(stderr, "- High-code CQL guidance now requires generated cqlQuery business reads to add the platform logical-delete predicate, commonly is_deleted = '0', for every queried business object or alias by default, only omitting it for explicit recycle-bin, deleted-record audit, or deletion-state comparison requirements.")
		fmt.Fprintln(stderr, "- Rollup summary field creation now stores summarizedObj/aggregateField in platform-readable API form, normalizes physical table/column inputs when catalogs are available, parses string conditionVals, and requires filtered summaries to include UI condition rows plus SQL conditions.")
		fmt.Fprintln(stderr, "- High-code business-source guidance now treats cquery* expressions as database-side business boundaries, documents the platform result limit risk, and forbids generated existence checks, duplicate checks, idempotency guards, and numbering prechecks from using 1=1 full-table reads followed by Java-side loops; generated classes, triggers, and timer classes must push business-key predicates into cqueryByFields/pagedQuery and select only needed fields.")
		fmt.Fprintln(stderr, "- High-code source-size guidance now requires generated classes, triggers, and timer-related custom classes to keep each Java file under 2000 lines and split complex requirements into multiple cooperating classes before one file becomes too large.")
		fmt.Fprintln(stderr, "- Field rollup summary creation now documents MetadataService specs for single and batch fields, compatible payload aliases, server-derived executeExpression/decimalPlaces/summaryfieldtype, and fail-closed filtered-summary SQL requirements.")
		fmt.Fprintln(stderr, "- Batch MetadataService create plans for objects, fields, and global select lists now report item-level precheck results in plan metadata: PLANNED, SKIPPED, or FAILED_PRECHECK with per-item error details, while keeping apply-time SQL execution batched and transactional.")
		fmt.Fprintln(stderr, "- Batch MetadataService create apply for objects, fields, and global select lists now documents async apply with {\"async\":true}, an applyId equal to operationId, and operation polling to avoid gateway timeout ambiguity.")
		fmt.Fprintln(stderr, "- Skill initialization now ships cloudcc-cli.config.json at the skill root with the public-cloud MetadataService default https://dc52.apis.cloudcc.cn/metadata; private-cloud initialization updates metadataService.url with the user's private endpoint.")
		fmt.Fprintln(stderr, "- Field docs now cover MetadataService batch add with fields[], onExisting createOnly/skipExisting/updateExisting/upsertByApiName, server-side duplicate API/dataFieldRef precheck, and object-local physical slot allocation.")
		fmt.Fprintln(stderr, "- Global select list docs now cover MetadataService batch add with globalSelectLists[], onExisting createOnly/skipExisting/updateExisting/upsertByApiName, and optionsMode none/append/merge/replace.")
		fmt.Fprintln(stderr, "- MetadataService compatibility matrix is now recorded in skill config.json; msapi.objects.batchCreate introduced in 2.2.10-msapi requires MetadataService 1.1.23 or later.")
		fmt.Fprintln(stderr, "- Page layout methodology docs now define reusable layout naming, section grouping, semantic field placement, related-list ordering, and review gates without tenant-specific scan evidence.")
		fmt.Fprintln(stderr, "- Object create now supports batch MetadataService specs with top-level objects[]; apply allocates unique setup-svc-compatible prefixes and datatable names per object under the target tenant lock, and docs show the plan/apply/readback flow.")
		fmt.Fprintln(stderr, "- Object create shortcuts now accept CloudCC default access with --accessable 0|1|2, passing accessable to MetadataService plans and the legacy setup-svc create body while preserving the existing default when omitted.")
		fmt.Fprintln(stderr, "- Global modeling field dictionary governance now treats the dictionary as a metadata disposition decision table: API selection uses explicit final-design APIs, structured API columns, English snake_case normalization, then Chinese pinyin fallback; non-field migration keys, source-code mappings, crosswalk-only rows, system fields, and global select lists must be classified before MSAPI plan generation.")
		fmt.Fprintln(stderr, "- High-code publish validation gate docs: cloudcc doc platform/classes|triggers|timer|almRelease devguide now documents class local compiler validation, target setup-svc validate (/api/ccfag/validate, /api/trigger/validate, /api/ccPeak/validate), setup-svc advisory baseline 19.3.R20, encoding rules, and structured validation failure responses.")
		fmt.Fprintln(stderr, "- High-code publish validation gate: starting with 2.2.7, classes, triggers, and timer require CLI publish support and recommend target setup-svc 19.3.R20+ support; classes publish runs local compiler validation then target setup-svc validate, while trigger/timer publish run target setup-svc validate before save.")
		fmt.Fprintln(stderr, "- Report create plans now preserve blank datarange values instead of defaulting to cury, matching main-svc saveReport semantics where blank means no quick date range.")
		fmt.Fprintln(stderr, "- Report filter docs and compiler regression now cover CSV multi-value conditions for contains-style operators, preserving values such as Active,Trial in conditionVals and tp_sys_condition rows.")
		fmt.Fprintln(stderr, "- Workflow MSAPI phase 1: workflow/workflowRule shortcuts now cover setup-web automation workflow list/detail, create/update/delete, and explicit enable/disable plans through MetadataService workflows.")
		fmt.Fprintln(stderr, "- Dual-provider UIAPI alignment: all 22 low-code domains and 97 baseline operations use source-proven UIAPI routes with local HTTP route/body contract coverage when UIAPI is selected. Shared input normalization keeps the stable CLI vocabulary aligned with MSAPI while retaining provider-specific safety semantics.")
		fmt.Fprintln(stderr, "- Report Matrix runtime closure: reportMatrix now validates chart/date prerequisites, and MetadataService plans expose mainobjectcolumnid closure sources plus Matrix row/column persistence mapping.")
		fmt.Fprintln(stderr, "- Field docs now explicitly require lookupObj/lookupObjectId to be the referenced object's tp_sys_object.ID, with custom-object examples that avoid API-name ambiguity.")
		fmt.Fprintln(stderr, "- Report typed CLI closure: reportTabular/reportSummary/reportMatrix/reportRatio now normalize main-svc saveReport payloads, validate type-specific required fields, preserve current service-zone report defaults, and generate ratio tbhbexpression from structured ratioExpressions.")
		fmt.Fprintln(stderr, "- Report Matrix CLI closure: reportMatrix create/update now normalizes Matrix payloads, validates row and column groups, source relation option/findId, selected fields, and maps main-svc ReportReqVo aliases into MetadataService report type custom data sources.")
		fmt.Fprintln(stderr, "- Standalone custom-class compiler/publisher: the skill packages cceg.jar, CloudCC cclib, and 30 integrity-checked compiler artifacts; doctor/validate/publish require only JDK 21, project source, and the target CloudCC public gateway, with no platform checkout, local setup-svc/main-svc, Maven cache, runtime URL, or binding.")
		fmt.Fprintln(stderr, "- Complete field-type metadata parity: all setup-svc public custom field types share one validated expansion path, including formula/summary, master-detail, address/location children, picklists, media/files, encryption, lookup filters, permissions, and delete cleanup.")
		fmt.Fprintln(stderr, "- Trigger save/publish now normalizes isactive/isActive values to boolean strings, so numeric 1/0 in local trigger specs are sent as true/false to setup-svc.")
		fmt.Fprintln(stderr, "- Report docs now match current MetadataService report persistence: source.objects drives reporttypecustom data sources, top-level objects drives tp_sys_report_object, invalid filter rows are skipped with compressed logic indexes, Matrix groups follow main-service storage semantics, and expression IDs are rebound to the saved report.")
		fmt.Fprintln(stderr, "- Report documentation cleanup: cloudcc doc report now describes only current MetadataService report/reportFolder usage and no longer mentions historical universal/apiSvc/page-request wording.")
		fmt.Fprintln(stderr, "- Report documentation refresh: cloudcc doc report now uses Chinese module docs and expands report/reportFolder parameters, report type semantics, filters, groups, summaries, charts, formulas, ratio reports, and folder membership rules.")
		fmt.Fprintln(stderr, "- Report DSL persistence closure: report/reportFolder plans now preserve report parameters into MetadataService tables, default reports without a folder to baf20200821lightning, treat foldertype report/lightning as report folders, and create new folders as lightning.")
		fmt.Fprintln(stderr, "- Field docs now preserve field type case semantics: lowercase c is currency, uppercase C is rollup summary.")
		fmt.Fprintln(stderr, "- setup-svc live replay reports parity now includes reports/folder-create, reports/folder-update, and reports/folder-delete as reports-domain variants with tp_sys_folder evidence.")
		fmt.Fprintln(stderr, "- Report/reportFolder CLI phase 1: report list/detail and reportFolder list/detail use MetadataService read endpoints, while report/reportFolder create/update/delete create reviewed reports-domain plans.")
		fmt.Fprintln(stderr, "- P0-P3 Go rewrite: doc/config/openapi/metadata/file publish foundations.")
		fmt.Fprintln(stderr, "- P4 partial: pagecomponent create/get/detail/pull/delete/doc plus publish of prebuilt UMD bundles.")
		fmt.Fprintln(stderr, "- customPage high-code closure: get/detail/create/update/delete customPage, publish-time customPageReferences hints, bind pagecomponent, safe package pagecomponent dry-run, and verify injectionPage diagnostics call CloudCC devconsole APIs directly without expanding MetadataService write domains.")
		fmt.Fprintln(stderr, "- customPage devconsole fix: customPage reads use accessToken before pluginToken, detail/delete send either id or pageApi but not both, CloudCC returnCode failures are honored before result, data.list list responses are covered, and bind pagecomponent supports --dry-run without saving customPage.")
		fmt.Fprintln(stderr, "- customPage bind/verify hardening: customPage save failures include the raw devconsole response body, save preflight checks pageContent/compList id consistency, and verify injectionPage can compare expected component id/version while reporting stale_component_reference instead of passing on name-only matches.")
		fmt.Fprintln(stderr, "- scheduleJob/customPage real protocol fix: scheduleJob uses schedulAbleprg and ccp lookup endpoints; customPage saves serialize pageContent/canvasStyleData to JSON strings and updates merge the current page id before devconsole save.")
		fmt.Fprintln(stderr, "- Trigger metadata CLI closure: trigger/triggers use the tp_sys_trigger setup-svc list/detail/save/delete contracts, online-highcode uses the global trigger list instead of the object-scoped empty query, selectors resolve to a unique id before detail/delete, and Java source plus signs survive URLDecoder-compatible encoding.")
		fmt.Fprintln(stderr, "- Profile read and safe-delete closure: get/detail profile use first-class MetadataService profile endpoints, preserve filters, resolve id/name/apiName uniquely, reject duplicate destructive selectors, and enforce system-admin/user-reference guards during plan and again under row locks at apply.")
		fmt.Fprintln(stderr, "- MetadataService field slot safety: field plans reserve existing tp_sys_schemetable mappings, allocate the first free object-local physical slot, reject explicit duplicates, and revalidate stale plans transactionally during apply.")
		fmt.Fprintln(stderr, "- Generic skill package cleanup: project-specific validation-rule write-window, production-readiness, field-map alias, legacy-script replacement commands, tests, fixtures, and reports are removed from the distributable skill.")
		fmt.Fprintln(stderr, "- MetadataService API integration: msapi capabilities/scan/resolve/validate/plan/apply/operation/changes/rollback/draft commands.")
		fmt.Fprintln(stderr, "- Go-only local scanner: scan msapi <projectPath> highcode reports classes/triggers/timer/script/html/staticResource/pagecomponent/sidecar and legacy Node scripts.")
		fmt.Fprintln(stderr, "- Go-only online scanner: scan msapi <projectPath> online-highcode reads classes/triggers/timer/script/staticResource/pagecomponent/html/customPage deployment list state without writes.")
		fmt.Fprintln(stderr, "- High-code write boundary guard: MetadataService plan/validate/mutate/draft-create rejects classes/triggers/timer/script/html/staticResource/pagecomponent/customPage domains; use the original CloudCC resource/API commands for those writes.")
		fmt.Fprintln(stderr, "- MetadataService scanner compare supports composite expected records, including object-scoped field API validation by object and field API name.")
		fmt.Fprintln(stderr, "- MetadataService scanner compare supports informational missing checks so display-label differences do not mask blocking gaps.")
		fmt.Fprintln(stderr, "- setup-svc live replay query-readback capture plan is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-query-readback-capture-plan expands the current 97-operation contract into concrete capture requests with pending artifact shapes, scanner commands, required tables, expectations, complete-worklist commands, bounded final-page offset/limit totals, and evidence-import gates without writing evidence or marking it passed.")
		fmt.Fprintln(stderr, "- setup-svc live replay query-readback capture plan now mirrors queryReadbackSources/total/returned/omitted counters at the top level and gives each capture request a scannerCommand so replay automation can consume the plan without reading nested totals or command arrays.")
		fmt.Fprintln(stderr, "- setup-svc live replay query-readback capture executor is available as an approval-gated apply mode: apply msapi <projectPath> setup-svc-live-replay-query-readback-capture calls standard-catalog and field-map read paths, self-checks strict query-readback source evidence, and writes mirrored captures only with CLOUDCC_SETUP_SVC_PARITY_QUERY_READBACK_CAPTURE_APPROVED.")
		fmt.Fprintln(stderr, "- setup-svc live replay MetadataService query scan capture is available as an approval-gated apply mode: apply msapi <projectPath> setup-svc-live-replay-metadata-service-query-scan-capture consumes metadata-service/query replacement records, calls read-only scanner paths, emits strict metadata-service tableSnapshots/runtimeEffectChecks evidence, and writes mirrored captures only with CLOUDCC_SETUP_SVC_PARITY_METADATA_SERVICE_QUERY_SCAN_CAPTURE_APPROVED.")
		fmt.Fprintln(stderr, "- setup-svc live replay MetadataService apply/query scan capture execute now blocks with blocked_metadata_service_datasource unless redacted MDS datasource readiness proves a real non-H2 datasource is configured.")
		fmt.Fprintln(stderr, "- setup-svc live replay metadata-service evidence now carries and verifies redacted metadataServiceDatasource proof; evidence without ready real datasource proof is rejected before import or completion.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion/source repair queues now route metadata-service datasource proof failures to metadata-service/metadataServiceDatasource, so old evidence missing redacted datasource proof gets a concrete capture checklist and worklist path.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-checklist operatorPacket now mirrors sourceFiles, targetFiles, replacementRecords, worklist queue/batch counts, missingSectionKinds, and nextQueueCount for script-friendly repair automation.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-execution operatorPacket now mirrors capture group totals, batch/import save command counts, runbook step count, datasource readiness, and completion-audit command for script-friendly capture orchestration.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-execution operatorBatches now mirror targetFiles next to sourceFiles so each capture batch can be reconciled independently without reading captureModeGroups.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-health missingSections and repairQueues now mirror targetFiles next to sourceFiles so each repair queue can be reconciled independently.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-health/source-checklist repairQueues now expose queue-scoped sourceExecutionCommand and saveSourceExecutionPacketCommand with evidence-section-specific packet paths.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit/evidence-import repairQueues now mirror sourceFiles/targetFiles and queue-scoped sourceExecutionCommand/saveSourceExecutionPacketCommand, so the final failedEvidenceSummary can save focused capture packets directly.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight captureSources now mirrors sourceFiles at top level and gate summary, and source-validate repairSummary now mirrors repairQueueCount for automation-friendly validation packets.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-checklist now mirrors sourceFiles/targetFiles/replacementRecords and repairQueueCount at the top level, and source-execution operatorBatches now expose batchPath as an alias for suggestedBatchPath.")
		fmt.Fprintln(stderr, "- setup-svc live replay worklist now mirrors sourceFiles and targetFiles at top level and operatorPacket, aligning worklist counters with source-checklist/source-health/source-validate outputs.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now keeps source-execution packet, batch-script, and import-script save commands in top-level nextCommands even when other preflight gates are blocked, so capture repair runbooks remain actionable from blocked_preflight output.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-validate operatorPacket now mirrors validation counters, failed artifact counts, skipped duplicates, repair queue count, and issue kind count for script-friendly pre-import gates.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-validate operatorPacket now mirrors repairQueues with copy-ready source-checklist/worklist commands, so pre-import validation output can be consumed as a complete repair packet.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-validate/evidence-import repairSummary now routes metadata-service datasource proof failures into metadata-service/metadataServiceDatasource repair queues, so pre-import validation gives copy-ready source-checklist and worklist commands.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence workspace templates now write operation-scoped requiredTables and runtimeEffects, so delete/query evidence placeholders match verifier semantics instead of carrying domain-wide write requirements.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit failedEvidenceSummary now mirrors repairQueueCount so final-gate repair automation can consume queue totals without deriving nested lengths.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit now mirrors failedEvidenceTotal and repairQueueCount at the top level for script-friendly final-gate status checks.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit totals now mirror failedEvidenceTotal and repairQueueCount, keeping final-gate counters consistent across top-level, totals, and failedEvidenceSummary.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight/environment metadata_service_datasource gates now carry a structured metadataServiceDatasource object in addition to summary counters, while preserving secret redaction.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit gates now carry structured summary objects for matrix contract, test evidence, live evidence, promotion audit, evidence bundle, and matrix-status gates.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit now mirrors gate summaries in a top-level gateSummaries map keyed by gate name for script-friendly final-gate reconciliation.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit now mirrors gate statuses in a top-level gateStatuses map keyed by gate name for script-friendly blocking checks.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit now emits a top-level operatorPacket that bundles final-gate status, gate maps, repair counters, datasource readiness, and next commands for automation.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit operatorPacket now carries repairQueues directly, so final-gate automation can save focused repair packets without reading failedEvidenceSummary.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit operatorPacket now carries failedEvidenceSummary directly, so final-gate automation can consume issue counts and repair queues from one packet.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit operatorPacket now carries blockingIssues directly, so final-gate automation can explain blockers from one packet.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit operatorPacket now carries failedEvidence directly, so final-gate automation can consume detailed failure rows from one packet.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit operatorPacket now carries per-domain completion details, so final-gate automation can identify blocked domains from one packet.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit now emits a repairPlan summary, grouping focused repair queues with primary source-execution commands for final-gate automation.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit repairPlan now maps failed domain/operation pairs to concrete repair queues, so final-gate automation can route each MSAPI operation gap to focused evidence capture batches.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit domains now carry domain-local repairPlan objects, so each blocked MSAPI domain can be repaired without scanning the global plan.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit repairPlan now exposes nextRepairCommands globally and per blocked domain for direct source-execution repair packet generation.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion-audit repairPlan now emits saveable nextRepairScript fields globally and per blocked domain for one-command repair packet script generation.")
		fmt.Fprintln(stderr, "- setup-svc live replay source execution packets are capture-mode aware: scan msapi <projectPath> setup-svc-live-replay-source-execution-packet --artifact-type metadata-service --capture-mode msapi_scan_snapshot_capture isolates query scan batches from write apply-capture batches.")
		fmt.Fprintln(stderr, "- setup-svc live replay source execution runbook steps now expose both batchPath and suggestedBatchPath so automation can read the capture-mode-specific batch file path without relying on a single field name.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion audit now exposes redacted metadataServiceDatasource readiness at the final gate, so missing real MDS_* datasource variables are visible next to live evidence blockers without leaking JDBC URL, username, or password values.")
		fmt.Fprintln(stderr, "- Page layout docs now include field semantic layout placement methodology so agents can choose business sections, balanced row/column positions, and PC/mobile placements for newly created fields instead of appending by creation order.")
		fmt.Fprintln(stderr, "- MetadataService/MSAPI HTTP calls now require an explicit endpoint. If CLOUDCC_METADATA_SERVICE_URL and the active project config are missing, the CLI prompts once for the URL and saves it under metadataService.url in the active env; non-interactive runs fail with a configuration hint instead of silently using localhost.")
		fmt.Fprintln(stderr, "- setup-svc live replay source health now mirrors sourceFiles/sourceFilesPresent/sourceFilesComplete/sourceFilesIncomplete/sourceFilesMissing and missingEvidenceSectionCounts at the top level for automation-friendly capture repair routing.")
		fmt.Fprintln(stderr, "- setup-svc live replay source validate now mirrors sourceFiles, artifactCount, readyArtifacts, failedArtifacts, and skippedDuplicateRecords at the top level while preserving artifacts as the detailed validation result list.")
		fmt.Fprintln(stderr, "- setup-svc live replay source execution runbook now emits dryRunCaptureCommand and executeCaptureCommand for query-readback, MetadataService apply capture, MetadataService query scan capture, and normalized diff stages, while marking setup-svc and cleanup stages as manualCaptureRequired.")
		fmt.Fprintln(stderr, "- setup-svc live replay source-health repairQueues now expose count and command aliases, and source-execution packets mirror sourceFiles/targetFiles/readiness/captureGroups/artifactTypes/domainOperations/evidenceSectionCount at the top level for automation-friendly replay orchestration.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence-import now consumes source-execution packet items directly and avoids doubling sourceRoot when item sourcePath already includes the mirrored capture root.")
		fmt.Fprintln(stderr, "- setup-svc live replay MetadataService apply capture is available as an approval-gated apply mode: apply msapi <projectPath> setup-svc-live-replay-metadata-service-apply-capture consumes metadata-service replacement records with planId, planRequest, captureTask.planRequest, or generated replay-safe planRequest, skips query operations for scan capture, calls MetadataService plan/apply, and writes operation result JSON files for snapshot-from-changes applyResultsDir only with CLOUDCC_SETUP_SVC_PARITY_METADATA_SERVICE_APPLY_CAPTURE_APPROVED.")
		fmt.Fprintln(stderr, "- setup-svc live replay snapshot-from-changes is available as an approval-gated apply mode: apply msapi <projectPath> setup-svc-live-replay-snapshot-from-changes converts inline operation changes or MetadataService operationId readback from /operations/{id}/changes into strict tableSnapshots/runtimeEffectChecks source evidence, accepts operationId from replacement records, source files, top-level operationResults/operationIds maps, operationResultsFile/applyResultsFile, or operationResultsDir/applyResultsDir, blocks missing raw changes, and writes mirrored captures only with CLOUDCC_SETUP_SVC_PARITY_SNAPSHOT_FROM_CHANGES_APPROVED.")
		fmt.Fprintln(stderr, "- setup-svc live replay source health is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-source-health summarizes mirrored capture source readiness, artifact-type/domain-operation health, missing evidence sections, and artifact-type-scoped repair queues without writing evidence or marking artifacts passed.")
		fmt.Fprintln(stderr, "- setup-svc live replay source validate is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-source-validate validates mirrored capture source files through the same strict evidence-import dry-run verifier before any import or manifest sync.")
		fmt.Fprintln(stderr, "- Standard CloudCC implementation methodology is embedded in delivery/global-modeling docs, including global object field dictionary governance, global select list references, and role/profile/security matrices.")
		fmt.Fprintln(stderr, "- MetadataService domains now expose implemented non-high-code security and platform domains, including roles, permissions, sharing-rules, menus, buttons, custom-settings, dupe-catchers, single-sign-ons, and identity-providers.")
		fmt.Fprintln(stderr, "- Sharing-rule reads now use dedicated MetadataService list/detail endpoints with object, filter and selector resolution, plus safe rule, condition, group and object projections.")
		fmt.Fprintln(stderr, "- Low-code metadata shortcuts are now closed over the MetadataService channel: create/update/delete/purge object and other low-code resource shortcuts create plans or scan through MetadataService instead of calling setup-svc directly.")
		fmt.Fprintln(stderr, "- Complete CLI command coverage: command-level tests now cover version/help/docs/config/project, OpenAPI CRUD/query, MetadataService scan/plan/apply/rollback/draft commands, low-code shortcuts, high-code resources, pagecomponent, schedule/user/staticResource, and deferred commands.")
		fmt.Fprintln(stderr, "- MetadataService object physical purge is plan/apply governed and now executes natively: plan msapi <projectPath> objects '{\"id\":\"<objid>\"}' physical-purge and apply with CLOUDCC_OBJECT_PHYSICAL_DELETE_APPROVED to run setup-svc-compatible cleanup with preflight, row counts, orphan cleanup, and verification evidence.")
		fmt.Fprintln(stderr, "- MSAPI custom object creation now normalizes implicit customer prefixes such as sun_ unless explicitly preserved, defaults English-only object descriptions to Chinese, and automatically expands setup-svc-compatible standard fields for new object intents.")
		fmt.Fprintln(stderr, "- MSAPI custom object apply now allocates setup-svc-compatible tp_sys_datatablestate values before execution, fills DATATABLE_NAME/PREFIX, rewrites prefix-derived tag field metadata, and lets authenticated CloudCC principals drive audit fields.")
		fmt.Fprintln(stderr, "- MetadataService/MSAPI parity replay now covers all supported low-code domains for create/update/delete/query shape, including query/readback completeness, layout/security/reference-data domains, and remaining approval/report/dashboard/view lifecycle cleanup.")
		fmt.Fprintln(stderr, "- setup-svc live replay readiness is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-readiness emits the approved replay evidence contract for promoting covered domains to verified.")
		fmt.Fprintln(stderr, "- setup-svc live replay environment check is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-environment reports redacted project config presence, MetadataService health, real datasource readiness for MDS_JDBC_URL/MDS_DB_USERNAME/MDS_DB_PASSWORD/MDS_DB_DRIVER, capture source readiness, and completion-audit status before live replay capture.")
		fmt.Fprintln(stderr, "- setup-svc live replay packet generation is available as a read-only scan/apply dry-run path: scan msapi <projectPath> setup-svc-live-replay-packet emits the current 22-domain/97-operation manifest template plus contractVersion/contractFingerprint, and apply msapi <projectPath> setup-svc-live-replay-packet @packet.json --dry-run validates the fingerprint, packet envelope, strict domain/operation set with no unexpected or duplicate entries, manifestTemplate, bundled parity-matrix-aligned requiredTables, requiredEvidence, and unique evidenceFiles contract without writes.")
		fmt.Fprintln(stderr, "- setup-svc live replay coverage audit is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-coverage reports current 22-domain/97-operation create/update/delete/query coverage, queryIncluded, setup-svc references, requiredTables, runtimeEffects, queryReadbackExpectations, matrix statuses, replay test evidence contract coverage, replay test source method checks, and variant operations such as physical-purge/assign/remove without writes.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight is available as a read-only aggregate scan mode: scan msapi <projectPath> setup-svc-live-replay-preflight combines readiness, packet dry-run, coverage, gap scan, evidence-bundle scan, and completion-audit gates so operators can see whether the workspace is ready for approved live replay before any setup-svc or MetadataService writes.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now treats pending evidence workspaces as evidence_collection_in_progress instead of blocked_preflight while strict evidence, promotion, and completion gates still reject pending placeholders.")
		fmt.Fprintln(stderr, "- setup-svc live replay workspace templates now declare strict artifact replacement checklists plus required snapshot, readback, normalized-diff, and cleanup evidence shapes so pending files guide real setup-svc evidence collection.")
		fmt.Fprintln(stderr, "- setup-svc live replay workspace execution now refuses to overwrite existing non-pending manifest/artifact evidence files, preserving collected passed/verified/success replay evidence while still allowing pending template refreshes.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence workspace preparation is approval-gated: apply msapi <projectPath> setup-svc-live-replay-workspace --dry-run previews the canonical manifest/artifact files, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_EVIDENCE_WORKSPACE_APPROVED writes pending JSON templates that the evidence verifier still rejects until real replay evidence replaces them.")
		fmt.Fprintln(stderr, "- setup-svc live replay normalized-diff generation is approval-gated: apply msapi <projectPath> setup-svc-live-replay-normalized-diff [manifest.json] --dry-run compares existing setup-svc and MetadataService table snapshots, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_NORMALIZED_DIFF_APPROVED writes normalized-diff.json artifacts and manifest normalizedDiffStatus values.")
		fmt.Fprintln(stderr, "- setup-svc live replay gap scanning is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-gaps reports missing manifests, pending workspace artifacts, failed artifact structures, and operations ready for normalized-diff generation before strict evidence verification.")
		fmt.Fprintln(stderr, "- setup-svc live replay gap scanning now emits a collectionPlan with artifact-type counts, explicit query-readback artifact coverage, required shape keys, and bounded next artifact actions for real evidence replacement.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan next artifact actions now include requiredTables plus runtimeEffects for snapshot artifacts and queryReadbackExpectations for query-readback artifacts, so evidence collectors can fill structure proof without opening each placeholder.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan now reports nextArtifactLimit and omittedNextArtifacts so large evidence workspaces cannot mistake the bounded nextArtifacts sample for the complete remaining artifact list.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan now supports --domain, --operation, --artifact-type, --status, --offset, and --limit on setup-svc-live-replay-gaps, and reports nextArtifactOffset, totalNextArtifacts, omittedNextArtifacts, and filters so evidence collectors can page through the full pending work queue.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan now emits pageCommands for current, next, and previous filtered pages so evidence collectors can continue large replay work queues without manually calculating offsets.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan next artifact actions now include replacementChecklist guidance aligned with workspace artifact templates, including snapshot, readback, normalized-diff, and cleanup proof requirements.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan next artifact actions now include manifestStatusField so evidence collectors know which manifest status is advanced by replacing each artifact and running manifest sync.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan next artifact actions now include requiredEvidenceSections so evidence collectors can machine-check required snapshot, readback, relationship, clean-counter, diff, and cleanup sections before manifest sync.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan next artifact actions now include evidenceSectionStatuses so pending or partially replaced artifacts expose which required sections are present or still missing.")
		fmt.Fprintln(stderr, "- setup-svc live replay collectionPlan now includes missingSectionQueues, a prioritized list of missing evidence sections with copy-ready queueCommand values for real replay evidence collection.")
		fmt.Fprintln(stderr, "- setup-svc live replay missingSectionQueues now include requiredShapeKey, manifestStatusField, pageSize, and batchCount so evidence collectors can plan section batches without opening individual artifacts.")
		fmt.Fprintln(stderr, "- setup-svc live replay missingSectionQueues now include bounded batchCommands plus omittedBatchCommands so operators can copy section-specific page commands without manually calculating offsets.")
		fmt.Fprintln(stderr, "- setup-svc live replay gap collectionPlan now emits a runbook with bounded evidence batch commands plus manifest-sync, evidence verification, evidence-bundle, promotion audit, and completion-audit steps.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now forwards gap collection runbook commands when evidence collection is already in progress, so operators continue with evidence replacement instead of restarting packet/workspace preparation.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now also surfaces worklist save commands for --source-status missing, --source-readiness complete, and --source-status present, followed by evidence-import dry-run/execute commands for complete captures, so mirrored captures can move directly from aggregate preflight to importable evidence batches.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now emits a captureSources summary and capture_sources gate that count canonical evidence files mirrored under captures/outputs/setup-svc-live-replay, making present/missing and complete/incomplete capture coverage visible before import.")
		fmt.Fprintln(stderr, "- setup-svc live replay capture-plan and worklist now mirror sourceFilesPresent/sourceFilesMissing/sourceFilesComplete/sourceFilesIncomplete into operator-facing packets and worklist top-level fields for simpler replay/diff reconciliation automation.")
		fmt.Fprintln(stderr, "- setup-svc live replay capture plan is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-capture-plan lists the 419 unique canonical replay artifacts, mirrored source capture paths, present/missing source status, required evidence sections, strict shape keys, manifest status fields, required tables, runtime effects, query-readback expectations, and copy-ready page/import commands without expanding duplicate section queues.")
		fmt.Fprintln(stderr, "- setup-svc live replay capture plan now separates source file presence from structural readiness: sourceReadiness complete/incomplete/missing, sourceFilesComplete/sourceFilesIncomplete counters, and --source-readiness filtering make half-filled captures visible before evidence import.")
		fmt.Fprintln(stderr, "- setup-svc live replay capture plan and worklist now emit captureTask blocks for every artifact and replacement record, including sourceSystem, captureMode, suggested source path, strict required evidence sections, source-readiness check command, and the approval-gated normalized-diff generation command where applicable.")
		fmt.Fprintln(stderr, "- setup-svc live replay capture source workspace is approval-gated: apply msapi <projectPath> setup-svc-live-replay-capture-source-workspace --dry-run previews mirrored captures/outputs/setup-svc-live-replay source templates, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_CAPTURE_SOURCE_WORKSPACE_APPROVED initializes missing capture source JSON files and safely upgrades existing pending/incomplete templates with top-level requiredShapeKey, manifestStatusField, and requiredEvidenceSections guidance without overwriting captured evidence.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now surfaces copy-ready capture-source-workspace dry-run and approved execute commands in captureSources and nextCommands, so missing mirrored source templates can be initialized directly from the aggregate gate before worklist import.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now suppresses missing-source initializer commands once all mirrored source templates exist, and routes operators to --source-readiness incomplete review worklists until real evidence makes captures complete.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion audit now forwards gap collection runbook commands when blocked by in-progress live replay evidence, so the final gate remains directly actionable.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion audit now also returns evidence-bundle and matrix-promotion nextCommands for blocked_evidence_bundle and ready_for_matrix_status_update, so the final gate can drive the post-evidence closure path.")
		fmt.Fprintln(stderr, "- setup-svc live replay preflight now forwards completion-audit stage nextCommands for blocked_evidence_bundle and ready_for_matrix_status_update, and treats complete gap scans as non-blocking so the aggregate gate continues into bundle and matrix closure instead of falling back to workspace preparation.")
		fmt.Fprintln(stderr, "- setup-svc live replay worklist is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-worklist expands missing evidence-section queues into concrete artifact batches, including query-readback files with required tables, readback expectations, section statuses, replacement checklists, mirrored sourceRoot capture paths, source-file presence and sourceReadiness counters, source-status/source-readiness filtering, and import commands.")
		fmt.Fprintln(stderr, "- setup-svc live replay worklist now supports --batch-index and --batch-limit, and filtered worklists only expand matching artifact-type/evidence-section queues so operators can pull a precise evidence replacement batch.")
		fmt.Fprintln(stderr, "- setup-svc live replay worklist now emits an operatorPacket and per-batch artifactReplacementRecords so each selected batch names target files, missing evidence sections, strict shape keys, manifest status fields, and the post-replacement sync/verify/bundle/promotion audit commands.")
		fmt.Fprintln(stderr, "- setup-svc live replay worklist now supports --source-readiness complete|incomplete|missing and carries sourceReadiness plus sourceFilesComplete/sourceFilesIncomplete so import worklists can exclude half-filled captures before evidence-import dry-run.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence-import now mirrors totals into top-level artifactCount/passedArtifacts/failedArtifacts/skippedDuplicateRecords/writtenFiles and echoes current batch worklist/import commands so blocked imports can continue on the same saved batch.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence-import now emits repairSummary for blocked batches, grouping failures by issue, missing evidence section, artifact type, and source capture file with captureTask guidance.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence-import repairSummary now includes repairQueues with copy-ready capture-plan, worklist, and save-worklist commands per artifact type and missing evidence section.")
		fmt.Fprintln(stderr, "- setup-svc live replay manifest sync is approval-gated: apply msapi <projectPath> setup-svc-live-replay-manifest-sync [manifest.json] --dry-run derives manifest statuses from existing artifact JSON files, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_MANIFEST_SYNC_APPROVED rewrites manifest.json without calling setup-svc, MetadataService, promotion, or matrix writes.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence bundle has a read-only verifier and approval-gated writer: scan msapi <projectPath> setup-svc-live-replay-evidence-bundle [manifest.json] reports whether evidence-bundle.json is missing, passed, stale, or blocked against the current manifest/artifact SHA-256 set; apply msapi <projectPath> setup-svc-live-replay-evidence-bundle [manifest.json] --dry-run computes coverage only after strict evidence verification passes, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_EVIDENCE_BUNDLE_APPROVED writes evidence-bundle.json for promotion audit archiving; matrix promotion apply and completion audit block if the bundle is missing, stale, or inconsistent with current evidence.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence verification is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-evidence blocks verified promotion unless the manifest project and contract fingerprint match the current project and packet contract and every domain/operation has passed setup-svc, MetadataService, query/readback, normalized diff, cleanup evidence, canonical packet-bound unique evidenceFiles paths, readable JSON evidence artifacts, artifact-level string passed/verified/success status, matching manifest and artifact project/contract/domain/operation/type identity, setup-svc and MetadataService tableSnapshots with per-required-table row evidence plus columns/primary-key evidence covering bundled parity-matrix-aligned requiredTables with matching setup-svc/MetadataService snapshot table sets per operation, query-readback structure proof with explicit fields/columns/queryShape/readbackShape evidence, non-empty requiredTables readback coverage, per-table actual row evidence, per-table field/column evidence, named passed relationshipChecks or source+target+field relationship structure, and numeric-zero clean counters, zero normalized diff missing/unexpected/mismatched numeric counters including nested diff/evidence/comparison nodes, and cleanup residual proof with numeric-zero remaining/residual/orphan/error counters; rowCount-only, columns-only, rowCount-plus-columns-only query readback, scalar keyed table placeholders, requiredRelationships-only lists, clean-counter-only readbackChecks, unnamed passed relationship checks, source-target-only relationships, failed/pending relationship checks, clean/ok/matched/no_diff markers, and boolean-only passed/success/verified flags are not accepted as completion evidence.")
		fmt.Fprintln(stderr, "- setup-svc live replay evidence bundle and promotion audit now surface strict runtimeEffectChecks/readbackExpectationChecks failures as domain/operation failedEvidence details so incomplete metadata proof can be repaired before bundle archival or verified promotion.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion audit now also surfaces strict runtimeEffectChecks/readbackExpectationChecks failures as blockingIssues and per-domain failedEvidence, making the final gate actionable before live evidence can be promoted.")
		fmt.Fprintln(stderr, "- setup-svc live replay matrixContract self-check now blocks readiness, packet generation, and evidence verification when the parity matrix is structurally incomplete; dupe-catchers, single-sign-ons, identity-providers, and reports now carry setup-svc source mappings and compiler-aligned requiredTables.")
		fmt.Fprintln(stderr, "- setup-svc live replay promotion audit is available as a read-only scan mode: scan msapi <projectPath> setup-svc-live-replay-promotion maps passed manifest evidence into covered->verified matrix update candidates without editing files.")
		fmt.Fprintln(stderr, "- setup-svc live replay matrix promotion apply is approval-gated: apply msapi <projectPath> setup-svc-live-replay-promotion --dry-run previews covered->verified matrix updates, while --execute --approval CLOUDCC_SETUP_SVC_PARITY_MATRIX_PROMOTION_APPROVED writes the located parity matrix only after evidence, evidence-bundle, and promotion audits pass.")
		fmt.Fprintln(stderr, "- setup-svc live replay completion audit is available as a read-only final gate: scan msapi <projectPath> setup-svc-live-replay-completion-audit combines matrixContract, replay test evidence/source-method contract, live replay evidence, evidence-bundle verification, promotion audit, and parity matrix statuses; it reports blocked_test_evidence_contract, blocked_missing_live_replay_evidence, blocked_live_replay_evidence, blocked_evidence_bundle, ready_for_matrix_status_update, or passed, and returns stage-specific nextCommands before it can pass.")
		fmt.Fprintln(stderr, "- P4 pure-Go Vue build replacement, JSP migration, and full MCP tool registration are intentionally deferred.")
		fmt.Fprintln(stderr)
	case "doctor":
		fmt.Fprintln(stdout, "cloudcc doctor")
		fmt.Fprintln(stdout, "- runtime: go binary")
		fmt.Fprintf(stdout, "- version: %s\n", Current())
		fmt.Fprintf(stdout, "- package: %s\n", edition.PackageName)
		fmt.Fprintf(stdout, "- default execution mode: %s\n", edition.DefaultExecutionMode)
		fmt.Fprintln(stdout, "- node/npm: not required by the Go skill runtime")
		fmt.Fprintln(stdout, "- pagecomponent publish: uploads an existing prebuilt UMD bundle and reports customPageReferences when readable")
	case "docs":
		fmt.Fprintln(stdout, "Use: cloudcc doc <layer>/<module> introduction|devguide")
	case "stats":
		fmt.Fprintln(stdout, "Command stats are not collected in the Go offline skill.")
	default:
		return fmt.Errorf("version: unsupported command %s", action)
	}
	return nil
}

func Help(stdout io.Writer, stderr io.Writer) int {
	fmt.Fprintln(stdout, "CloudCC CLI Go")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Usage:")
	fmt.Fprintln(stdout, "  cloudcc --version")
	fmt.Fprintln(stdout, "  cloudcc doc <layer>/<module> introduction|devguide")
	fmt.Fprintln(stdout, "  cloudcc doctor project-governance [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc init project-outputs <projectPath> <projectCode>")
	fmt.Fprintln(stdout, "  cloudcc doctor project-outputs [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc init test-governance <projectPath> <projectCode>")
	fmt.Fprintln(stdout, "  cloudcc advise testing <projectPath> <@change.json|json>")
	fmt.Fprintln(stdout, "  cloudcc decide testing <projectPath> <@decision.json|json>")
	fmt.Fprintln(stdout, "  cloudcc record testing <projectPath> <@run.json|json>")
	fmt.Fprintln(stdout, "  cloudcc doctor test-governance [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc get config [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc use config <env> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc create project <name|.>")
	fmt.Fprintln(stdout, "  cloudcc <query|pageQuery|create|update|delete|upsert> openapi <projectPath> <encodedBodyJson> [isMcp]")
	fmt.Fprintln(stdout, "  cloudcc capabilities msapi [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc scan msapi [projectPath] [summary|standard-catalog|project|highcode|online-highcode|setup-svc-live-replay-readiness|setup-svc-live-replay-environment|setup-svc-live-replay-packet|setup-svc-live-replay-coverage|setup-svc-live-replay-preflight|setup-svc-live-replay-evidence|setup-svc-live-replay-gaps|setup-svc-live-replay-capture-plan|setup-svc-live-replay-worklist|setup-svc-live-replay-source-checklist|setup-svc-live-replay-source-health|setup-svc-live-replay-source-validate|setup-svc-live-replay-source-execution-packet|setup-svc-live-replay-evidence-bundle|setup-svc-live-replay-promotion|setup-svc-live-replay-completion-audit|local|@compareRequest.json]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-packet <@packet.json|packetJson> [--dry-run]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-workspace [@packet.json] [--dry-run|--execute --approval CLOUDCC_SETUP_SVC_PARITY_EVIDENCE_WORKSPACE_APPROVED]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-normalized-diff [manifest.json] [--dry-run|--execute --approval CLOUDCC_SETUP_SVC_PARITY_NORMALIZED_DIFF_APPROVED]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-manifest-sync [manifest.json] [--dry-run|--execute --approval CLOUDCC_SETUP_SVC_PARITY_MANIFEST_SYNC_APPROVED]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-evidence-bundle [manifest.json] [--dry-run|--execute --approval CLOUDCC_SETUP_SVC_PARITY_EVIDENCE_BUNDLE_APPROVED]")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] setup-svc-live-replay-promotion [manifest.json] [--dry-run|--execute --approval CLOUDCC_SETUP_SVC_PARITY_MATRIX_PROMOTION_APPROVED]")
	fmt.Fprintln(stdout, "  cloudcc resolve msapi [projectPath] <encodedReferencesJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc <normalize|validate|plan> msapi [projectPath] <domain> <encodedSpecJson|@file> [operation]")
	fmt.Fprintln(stdout, "  cloudcc plan msapi [projectPath] objects '{\"id\":\"<objid>\"}' physical-purge")
	fmt.Fprintln(stdout, "  cloudcc apply msapi [projectPath] <planId> [encodedApplyRequest|@file]")
	fmt.Fprintln(stdout, "  cloudcc <operation|changes|rollback-plan|rollback> msapi [projectPath] <operationId>")
	fmt.Fprintln(stdout, "  cloudcc mutate msapi [projectPath] <domain> <mutation> <encodedPatchOrSpecJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc <draft-create|draft-update|draft-validate|draft-plan|draft-delete> msapi ...")
	fmt.Fprintln(stdout, "  cloudcc <normalize|validate|plan|apply|operation|changes|rollback-plan|rollback> metadata ...")
	fmt.Fprintln(stdout, "  cloudcc get trigger <projectPath> [nameOrQueryJson]")
	fmt.Fprintln(stdout, "  cloudcc detail trigger <projectPath> <id|name|apiName>")
	fmt.Fprintln(stdout, "  cloudcc <create|update|save> trigger <projectPath> <triggerJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc delete trigger <projectPath> <id|name|apiName>")
	fmt.Fprintln(stdout, "  cloudcc get profile <projectPath> [filter]")
	fmt.Fprintln(stdout, "  cloudcc detail profile <projectPath> <id|name|apiName>")
	fmt.Fprintln(stdout, "  cloudcc delete profile <projectPath> <id|name|apiName>  # resolves uniquely and creates a guarded MetadataService plan")
	fmt.Fprintln(stdout, "  cloudcc get report <projectPath> [folderId] [searchKeyWord] [page] [pageSize] [orderField] [orderType]")
	fmt.Fprintln(stdout, "  cloudcc detail report <projectPath> <reportId|encodedBodyJson>")
	fmt.Fprintln(stdout, "  cloudcc create report <projectPath> <encodedReportJson>")
	fmt.Fprintln(stdout, "  cloudcc update report <projectPath> <reportId> <encodedReportJson>")
	fmt.Fprintln(stdout, "  cloudcc create reportTabular <projectPath> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc update reportTabular <projectPath> <reportId> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc create reportSummary <projectPath> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc update reportSummary <projectPath> <reportId> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc create reportMatrix <projectPath> <encodedMatrixReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc update reportMatrix <projectPath> <reportId> <encodedMatrixReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc create reportRatio <projectPath> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc update reportRatio <projectPath> <reportId> <encodedReportJson|@file>")
	fmt.Fprintln(stdout, "  cloudcc delete report <projectPath> <reportId> [confirmdelete]")
	fmt.Fprintln(stdout, "  cloudcc get reportFolder <projectPath> [searchKeyWord]")
	fmt.Fprintln(stdout, "  cloudcc detail reportFolder <projectPath> <folderId|encodedBodyJson>")
	fmt.Fprintln(stdout, "  cloudcc create reportFolder <projectPath> <name> [encodedOptionsJson]")
	fmt.Fprintln(stdout, "  cloudcc update reportFolder <projectPath> <folderId> <encodedOptionsJson>")
	fmt.Fprintln(stdout, "  cloudcc delete reportFolder <projectPath> <folderId>")
	fmt.Fprintln(stdout, "  cloudcc publish trigger <objectApi/TriggerName> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc doctor classes [projectPath] [--java-home <path>] [--compiler-home <path>]")
	fmt.Fprintln(stdout, "  cloudcc prepare classes [projectPath]  # compatibility alias: verify packaged compiler")
	fmt.Fprintln(stdout, "  cloudcc validate classes <ClassName> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc publish classes <ClassName> [projectPath] [--validation-evidence <file>]")
	fmt.Fprintln(stdout, "  cloudcc publish timer <TimerName> [projectPath]")
	fmt.Fprintln(stdout, "  # classes publish runs local compiler validation then remote setup-svc validate; triggers/timer publish run remote validate then save")
	fmt.Fprintln(stdout, "  cloudcc create pagecomponent <name>")
	fmt.Fprintln(stdout, "  cloudcc package pagecomponent <name> [projectPath] --dry-run")
	fmt.Fprintln(stdout, "  cloudcc publish pagecomponent <name> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc bind pagecomponent <projectPath> <pageApi> <componentIdOrName> [--embedded true|false] [--workspace-url <url>] [--dry-run]")
	fmt.Fprintln(stdout, "  cloudcc get pagecomponent [projectPath] [compName]")
	fmt.Fprintln(stdout, "  cloudcc detail pagecomponent <name> [id] [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc pull pagecomponent <nameOrId> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc delete pagecomponent <nameOrId> [projectPath]")
	fmt.Fprintln(stdout, "  cloudcc get customPage <projectPath> [pageApi]")
	fmt.Fprintln(stdout, "  cloudcc detail customPage <projectPath> <pageApi|id>")
	fmt.Fprintln(stdout, "  cloudcc create customPage <projectPath> <payload|@file>")
	fmt.Fprintln(stdout, "  cloudcc update customPage <projectPath> <pageApi|id> <payload|@file>")
	fmt.Fprintln(stdout, "  cloudcc delete customPage <projectPath> <pageApi|id>")
	fmt.Fprintln(stdout, "  cloudcc verify injectionPage <projectPath> <pageApi> [--expected-component <id|name>] [--expected-component-id <id>] [--expected-component-version <version>] [--stale-policy warning|failure] [--snapshot <@json|json>]")
	fmt.Fprintln(stdout, "  cloudcc <get|detail> <low-code-resource> <projectPath> ...  # MetadataService scan")
	fmt.Fprintln(stdout, "  cloudcc <create|update|delete|purge> <low-code-resource> <projectPath> ...  # MetadataService plan only")
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Naming: pagecomponent is the only supported resource name for CloudCC page custom components.")
	fmt.Fprintln(stdout, "Deferred: pure-Go Vue build replacement, JSP migration, full MCP tool registration.")
	return 0
}

func normalize(action string) string {
	switch strings.TrimSpace(action) {
	case "version", "-version", "--version", "-v", "--v":
		return "get"
	case "help", "-help", "--help", "-h", "--h":
		return "help"
	default:
		return action
	}
}
